// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-cBfMHb-Yb5L2UCO-r0wrR-djP47FZI',
    appId: '1:934100035583:web:10caf881d88b9e298aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    authDomain: 'jaga-app-3e0ef.firebaseapp.com',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
    measurementId: 'G-VD0NSXVGSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-nT0ttF7CvwqceqadkBazlIuQI0xG-4',
    appId: '1:934100035583:android:22264fbb0cb499ce8aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbIAcumM5zsXAIrpd4Qfnap4ObCWirWY',
    appId: '1:934100035583:ios:3c2805ea2a074b128aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
    iosBundleId: 'com.example.jagaAppAdmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbIAcumM5zsXAIrpd4Qfnap4ObCWirWY',
    appId: '1:934100035583:ios:3c2805ea2a074b128aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
    iosBundleId: 'com.example.jagaAppAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-cBfMHb-Yb5L2UCO-r0wrR-djP47FZI',
    appId: '1:934100035583:web:9c49f76d46b386688aa9ca',
    messagingSenderId: '934100035583',
    projectId: 'jaga-app-3e0ef',
    authDomain: 'jaga-app-3e0ef.firebaseapp.com',
    storageBucket: 'jaga-app-3e0ef.firebasestorage.app',
    measurementId: 'G-0R78X1PW9C',
  );

}